defaults: &defaults
  working_directory: ~/oya-project
  docker:
    - image: circleci/ruby:2.5-node-browsers
      environment:
        OYA_VER: "oya version v0.0.15"
        PATH: ~/.oya/bin:$PATH

version: 2
jobs:
  oya_dependencies:
    <<: *defaults
    steps:
      - run: apt-cache update && apt-get install -y wget
      - run: wget https://github.com/tooploox/oya/releases/download/v0.0.15/oya_v0.0.15_linux_amd64.gz
      - run: gunzip oya_v0.0.15_linux_amd64.gz && mv oya_v0.0.15_linux_amd64 oya
      - run: chmod +x oya
      - run: mkdir -p ~/.oya/bin
      - run: mv oya ~/.oya/bin
      - run: oya version

  onPush:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/oya-project
      - run: ./oya run onPush


  onMergeToMaster:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/oya-project
      - run: ./oya run onMergeToMaster

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - oya_dependencies
      - onPush:
          requires:
            - oya_dependencies

      - onMergeToMaster:
          requires:
            - oya_dependencies

